echo "Welcome to use attackMap By Luckykeeper in Docker!!!"
echo "github: https://github.com/luckykeeper/attackMap"
echo "当前系统参数如下所示:"
echo "调试模式 = ${debug}"
echo "syslog 服务器 IP = ${syslog_host}"
echo "syslog 服务器端口 = ${syslog_port}"
echo "MongoDB 服务器 IP 地址 = ${MongoDB_host}"
echo "MongoDB 服务器用户 = ${MongoDB_user}"
echo "MongoDB 服务器密码 = ${MongoDB_password}"
echo "MongoDB 服务器写入数据库 = ${MongoDB_Syslog_dbName}"
echo "MongoDB 服务器写入 Collection = ${MongoDB_Syslog_col}"
echo "MongoDB 服务器备份 Collection = ${MongoDB_Backup_col}"
echo "MongoDB 服务器展示数据库 = ${MongoDB_show_dbName}"
echo "MongoDB 服务器展示 Collection = ${MongoDB_show_col}"
echo "内部输出告警文件名称 = ${outputCsvName}"
echo "原始数据保留周期(天) = ${deletePeriods}"
echo "告警邮件发件人邮箱 = ${email_sender}"
echo "告警邮件发件人密码/授权码 = ${mail_Password}"
echo "告警邮件收件人邮箱 = ${mail_Receiver}"
echo "告警邮件发件人显示昵称 = ${email_sender_name}"
echo "SMTP 服务器地址 = ${email_smtp_server}"
echo "SMTP 服务器端口 = ${email_smtp_server_port}"
echo "经度 = ${destLocX}"
echo "纬度 = ${destLocY}"


echo " —————————————————程序开始运行！———————————————————————"
echo "Powered By Luckykeeper<luckykeeper.site|luckykeeper@luckykeeper.site>"
echo " —————————————————代码和人必有一个能润起来！———————————————————————"

python3 /usr/src/app/pysyslog/sysloger.py